### ISSUE TITLE
Potential improvements from STAC community meeting

### ISSUE THREAD

**Issue by m-mohr** [crim-ca/dlm-extension#5]
Potential improvements identified in the STAC call today:

- normalization:* fields should not use :, instead use _
- flatten architecture object and any other non-array dlm:* field
- clarify whether the other fields are actually arrays of objects and not just objects (e.g. currently you can only have one input and output each as per the spec)
- some fields should re-use existing fields (e.g. class_name_mapping could use classification:classes)
- remove the section "Relation types" if unused

**Comment by rbavery** [comment]
Thanks for posting these!

I think folks reviewed the current extension spec. I've addressed these and other improvements in this PR, it might be good to review this PR instead at the next call since the extension has been revamped a lot with mine and @fmigneault 's input. hackmd for that version is here and available for comment: https://hackmd.io/DBRF1sQCS1WmSqygJNKQJQ?view

> normalization:* fields should not use :, instead use _

done in #2 

> flatten architecture object and any other non-array dlm:* field

will do in #2 I'll keep all parameters relevant to search flat and use objects for parameters that are more relevant for loading and processing

> clarify whether the other fields are actually arrays of objects and not just objects (e.g. currently you can only have one input and output each as per the spec)

done in #2 

> some fields should re-use existing fields (e.g. class_name_mapping could use classification:classes)

will do!

> remove the section "Relation types" if unused

I'm still unsure how this extension will be referenced. there's a discussion in #3 a custom relation type sounds like one option. curious to hear what other folks think is best.

**Comment by rbavery** [comment]
these comments are addressed except for "Relation types" which is still being discussed in #3

**Comment by fmigneault** [comment]
All addressed including "Relation types". Fixed by #2
