### ISSUE TITLE
handle multiple model artifacts that are associated with a model

### ISSUE THREAD

**Issue by rbavery** [crim-ca/dlm-extension#9]
As I'm working with [AOTIndutor](https://www.youtube.com/watch?v=w7d4oWzwZ0c) and [Torchscript](https://pytorch.org/docs/stable/jit.html) for exporting models, I'm realizing that model publishers will sometimes want to reference runtime details for multiple model artifacts, without duplicating all model extension info.

AOTInductor (.pt2) exports a model with hardware specific optimizations, so it will be tied to a particular accelerator (cpu, gpu, tpu, etc.)

Torchscript tracing (.pt) is hardware agnostic. the loaded model and model inputs just need to be moved to the correct hardware before inference. The optimizations are not hardware specific so accelerator utilization is lower than models compiled with AOTInductor.

Model publishers might want to provide any of combinations of a hardware agnostic model artifact, multiple optimized models, or the original weights.

I think we should probably accept an array of Runtime Objects instead of a single Runtime Object.

**Comment by rbavery** [comment]
done in #2 and updated the [hackmd](https://hackmd.io/DBRF1sQCS1WmSqygJNKQJQ?both#Item-Properties-and-Collection-Fields)

**Comment by fmigneault** [comment]
Various model artifacts should be provided by distinct Assets with `mlm:model` role. 
Each Asset can also provide `mlm:artifact_type` to be more explicit about the specific artifact content.
Other fields such as `mlm:framework` can also be applied on individual Assets to allow providing multiple equivalent definitions by various implementations. 

Fixed by #2
